name: GitHub Actions / Linting, Testing, Building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: Assemble Production
        run: npm run build:prod
      - name: TS linting
        run: npm run eslint
      - name: CSS linting
        run: npm run stlint
      - name: Unit testing (JEST)
        run: npm run test:unit
      - name: StoryBook build (STORYBOOK testing)
        run: npm run storybook:build
      - name: Screenshot testing (LOKI testing)
        run: npm run test:loki:ci